description = "Core Platform Engineer @ n8n and Web Tech nerd"

author = "Mike Repeć"

[social]
github = "https://github.com/Flexicon"
linkedin = "https://www.linkedin.com/in/mikerepec/"
twitter = "https://x.com/flexicondev"
feed = "/index.xml"
