[[redirects]]
  from = "https://flexicondev.com/*"
  to = "https://flexicon.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.flexicondev.com/*"
  to = "https://flexicon.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://blog.flexicondev.com/*"
  to = "https://blog.flexicon.dev/:splat"
  status = 301
  force = true

