[build]
  publish = "public"
  command = "make build"

[build.environment]
  HUGO_VERSION = "0.151.0"
  NODE_VERSION = "22.18.0"
  NPM_VERSION = "11.6.1"

[[redirects]]
  from = "https://flexicondev.com/*"
  to = "https://flexicon.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.flexicondev.com/*"
  to = "https://flexicon.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://blog.flexicondev.com/*"
  to = "https://blog.flexicon.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/relay-bbib/static/*"
  to = "https://eu-assets.i.posthog.com/static/:splat"
  host = "eu-assets.i.posthog.com"
  status = 200
  force = true

[[redirects]]
  from = "/relay-bbib/*"
  to = "https://eu.i.posthog.com/:splat"
  host = "eu.i.posthog.com"
  status = 200
  force = true
